### ISSUE TITLE
User input GUI

### ISSUE THREAD

**Issue by evangineer** [nyacg/PromptFlow#1]
Will receive a JSON object containing the following:
* Name (String)
* Description (String)
* Inputs (Array of Names and Descriptions)

Title                                                                                               Edit button
Desc

Input box 1
Input box 2.
etc

![Prompt Flow input GUI - rotated](https://user-images.githubusercontent.com/53523/233807763-e6ba2187-0daf-4574-87e7-9626d2ba468e.jpg)

**Comment by olasofia** [comment]
import React, { useState } from 'react';

interface InputSpec {
  name: string;
  description?: string;
}

interface FlowSpec {
  title: string;
  description: string;
  inputs: InputSpec[];
}

const landingPageFlowSpec: FlowSpec = {
  title: 'Landing Page Generator',
  description:
    "Give us a few details about your product and we'll generate a simple email collection landing page for you",
  inputs: [
    {
      name: 'Product name',
    },
    {
      name: 'Industry',
    },
    {
      name: 'Description',
      description:
        'A brief description about your offering, feel free to use bullet points',
    },
  ],
};

const LandingPageForm: React.FC = () => {
  const [formValues, setFormValues] = useState({});

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setFormValues({
      ...formValues,
      [event.target.name]: event.target.value,
    });
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    console.log(formValues);
  };

  return (
    <div>
      <h1>{landingPageFlowSpec.title}</h1>
      <p>{landingPageFlowSpec.description}</p>
      <form onSubmit={handleSubmit}>
        {landingPageFlowSpec.inputs.map((input, index) => (
          <div key={index}>
            <label htmlFor={input.name}>{input.name}</label>
            <input
              type="text"
              id={input.name}
              name={input.name}
              placeholder={input.description}
              onChange={handleChange}
            />
          </div>
        ))}
        <button type="submit">Submit</button>
      </form>
    </div>
  );
};

export default LandingPageForm;

**Comment by olasofia** [comment]
[input.txt](https://github.com/nyacg/PromptFlow/files/11302379/input.txt)

**Comment by olasofia** [comment]
[index.txt](https://github.com/nyacg/PromptFlow/files/11302432/index.txt)

**Comment by evangineer** [comment]
So, we need to:

* Make it run
* Make it right
* Make it ~~fast~~ pretty

**Comment by olasofia** [comment]
[styles.txt](https://github.com/nyacg/PromptFlow/files/11302538/styles.txt)

**Comment by olasofia** [comment]
`<link rel="stylesheet" href="styles.css">`

**Comment by olasofia** [comment]
[styles-1.txt](https://github.com/nyacg/PromptFlow/files/11302546/styles-1.txt)

**Comment by olasofia** [comment]
`import '../styles.css';`

**Comment by olasofia** [comment]
```
here is the stuff
```

**Comment by evangineer** [comment]
Okay, so we have a not so ugly interface.

Now we need to make it dynamic: 

1. Load and display the selected json.
1. Submit the user's input data to the server as a json object with the id of the user, flow and the actual input values.

**Comment by evangineer** [comment]
https://github.com/nyacg/PromptFlow/commit/d62092a5841e4187bedb6f288d212ec27ab5b18c
